### ISSUE TITLE
Cannot find function locate_crate_paths in crate i18n_config

### ISSUE THREAD

**Issue by Casara** [kellpossible/cargo-i18n#65] opened 2021-03-18 02:58 UTC
The following error is occurring when using version 0.11.0 of the i18n-embed sub crate:

```
error[E0425]: cannot find function `locate_crate_paths` in crate `i18n_config`
  --> /home/casara/.asdf/installs/rust/1.50.0/registry/src/github.com-1ecc6299db9ec823/i18n-embed-impl-0.7.0/src/lib.rs:32:41
   |
32 |     let config_file_path = i18n_config::locate_crate_paths()
   |                                         ^^^^^^^^^^^^^^^^^^ not found in `i18n_config`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `i18n-embed-impl`
```

The function `locate_crate_paths` was introduced in version [0.4.1](https://github.com/kellpossible/cargo-i18n/blob/master/i18n-config/CHANGELOG.md#v041) of the i18n-version sub crate as seen in the link.

However, in version 0.11.0 of i18n-embed, its sub crate i18n-embed-impl uses version 0.4.0 of i18n-config: https://github.com/kellpossible/cargo-i18n/blob/master/i18n-embed/i18n-embed-impl/Cargo.toml#L21.

Version 0.3.1 of the sub crate i18n-embed-fl is also using version 0.4.0 of i18n-config and [calling the function `locate_crate_paths`](https://github.com/kellpossible/cargo-i18n/blob/master/i18n-embed-fl/src/lib.rs#L290): https://github.com/kellpossible/cargo-i18n/blob/master/i18n-embed-fl/Cargo.toml#L19.

For the time being, I solved it by adding version 0.4.1 of the i18n-config box to Cargo.toml.

**Comment by kellpossible** [comment] 2021-03-18 06:09
@Casara thanks for reporting! A confusing dependency problem :thinking: Do you have any opinions on the best way to push a fix for this?

**Comment by kellpossible** [comment] 2021-03-18 06:14
Have you tried doing a `cargo update  -p 18n-embed`? I don't think any of the dependencies specified are specifically locked to `0.4.0` of `i18n-config`. Seems like maybe some kind of incompatibility in your lock file?

**Comment by kellpossible** [comment] 2021-04-25 06:24
@Casara did you get a chance to look at this again?

**Comment by Casara** [comment] 2021-05-03 14:31
> @Casara did you get a chance to look at this again?

Not yet, I'm very busy at the moment. I do not know when I can stop to look at it again.

**Comment by kellpossible** [comment] 2021-05-09 19:49
Okay no worries, I'm going to close this issue for now because I can't reproduce it, but if you do get a chance to look at it let me know and I'll re-open if needed.

**Closed by kellpossible** 2021-05-09 19:49 UTC

**Comment by kellpossible** [comment] 2021-05-19 04:36
I just ran into this issue updating one of my own projects. I was able to resolve it with `cargo update -p i18n-config` Looks like there was probably a breaking change in i18n-config that needed a bigger version bump.
